version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    command: -p 1223
    expose:
      - 1223
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/fastapi_app/app.sh" ]
    ports:
      - 9999:8000
    depends_on:
      - db

