"""updates

Revision ID: 14959be59a6e
Revises: 
Create Date: 2023-06-29 18:15:47.196184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14959be59a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobdraft_company_name', table_name='jobdraft')
    op.drop_table('jobdraft')
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_active')
    op.create_table('jobdraft',
    sa.Column('id_job', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posted_days_ago', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_job', name='jobdraft_pkey'),
    sa.UniqueConstraint('name', name='jobdraft_name_key')
    )
    op.create_index('ix_jobdraft_company_name', 'jobdraft', ['company_name'], unique=False)
    # ### end Alembic commands ###
