"""updates

Revision ID: 54e4a59eadb2
Revises: 14959be59a6e
Create Date: 2023-06-29 18:17:16.302835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4a59eadb2'
down_revision = '14959be59a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
