"""news uuidss

Revision ID: 76129128e82f
Revises: b93da7039dd8
Create Date: 2023-06-14 20:39:45.913868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76129128e82f'
down_revision = 'b93da7039dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
