"""jobs

Revision ID: a86c015de176
Revises: f27dd500dc9f
Create Date: 2023-06-18 23:30:52.572615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86c015de176'
down_revision = 'f27dd500dc9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
