"""news uuid

Revision ID: bd6ffea5dc25
Revises: 1eae59ca299c
Create Date: 2023-06-14 20:15:42.221064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6ffea5dc25'
down_revision = '1eae59ca299c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
